#application
server:
  port: 50900
  tomcat.threads.max: 20

#monitoring
management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "health,prometheus,heapdump"

#openapi
springdoc.swagger-ui.path: /swagger-ui/index.html
springdoc.enable-native-support: "true"

#jaeger / zipkin
spring.application.name: callee-service
management.zipkin.tracing.endpoint: "http://localhost:9411/api/v2/spans"
management.tracing.sampling.probability: "1.0"
management.tracing.propagation.type: "B3"
management.tracing.enabled: "true"

#security
security.authentication.enabled: true
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope:
              - openid
            client-id: oauth2-proxy
            clientSecret: none
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
#            issuerUri: http://127.0.0.1:30200
#            issuerUri: http://localhost:30200/oidc/realms/tenant-0

            auth-base-uri: http://localhost:30200/oauth2

#            auth-base-uri: http://localhost:30200/oidc/realms/tenant-0/protocol/openid-connect
#            user-name-attribute: preferred_username

            authorization-uri: ${spring.security.oauth2.client.provider.keycloak.auth-base-uri}/auth
            token-uri: ${spring.security.oauth2.client.provider.keycloak.auth-base-uri}/token
            userinfo-uri: ${spring.security.oauth2.client.provider.keycloak.auth-base-uri}/userinfo
            jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.auth-base-uri}/certs

#logging
logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

