#security
security.authentication.enabled: true
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope:
              - openid
            client-id: oauth2-proxy
            clientSecret: none
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
#            issuerUri: http://127.0.0.1:30200
#            issuerUri: http://localhost:30200/oidc/realms/tenant-0

            auth-base-uri: http://localhost:30200/oauth2

#            auth-base-uri: http://localhost:30200/oidc/realms/tenant-0/protocol/openid-connect
#            user-name-attribute: preferred_username

            authorization-uri: ${spring.security.oauth2.client.provider.keycloak.auth-base-uri}/auth
            token-uri: ${spring.security.oauth2.client.provider.keycloak.auth-base-uri}/token
            userinfo-uri: ${spring.security.oauth2.client.provider.keycloak.auth-base-uri}/userinfo
            jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.auth-base-uri}/certs

