#logging
logging.level.root: "WARN"
logging.level.org.springframework: "INFO"
logging.level.org.goafabric: "INFO"


#s3
spring.cloud.aws.s3.enabled: "true"
spring.cloud.aws.s3.path-style-access-enabled: "true"
spring.cloud.aws.s3.endpoint: "http://localhost:9100" #"http://s3.localhost.localstack.cloud:4566"
spring.cloud.aws.credentials.access-key: "minioadmin"
spring.cloud.aws.credentials.secret-key: "minioadmin"
spring.cloud.aws.region.static: "eu-central-1" #"us-east-1" //for localstack s3 + native client us-east seems to be needed

#azure
azure:
  storage:
    url: http://localhost:10000/%s # local url for azurite
    #url: https://%s.blob.core.windows.net # remote url on azure
    account-name: devstoreaccount1
    account-key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==


multi-tenancy.schema-prefix: "callee_"
blob.storage.implementation: "azure"

provision:
  namespaces: "example,core,billing"
  tenants: "0,5" #"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99"
  mode: "create" #"update"
  maxUpdatePods: "8"
  inMemory: "false"
