#application
server:
  port: 50900
  tomcat.threads.max: 20
  forward-headers-strategy: FRAMEWORK

#vthreads
spring.threads.virtual.enabled: "true"

#monitoring
management:
    endpoint:
      health:
        show-details: never
    endpoints:
      web:
        exposure:
          include: "health,prometheus,heapdump"

#tracing
spring.application.name: callee-service
management.tracing.sampling.probability: "1.0"
management.opentelemetry.tracing.export.otlp.endpoint: "http://localhost:4318/v1/traces"
logging.level.io.opentelemetry: "OFF"

#management.otlp.metrics.export.url: "http://otel-collector:4318/v1/metrics" #otel collector (prometheus) metrics endpoints, currently disabled because not used
management.otlp.metrics.export.enabled: false

#logging
logging.pattern.level: "%5p tenantId=%X{tenantId:-}" #"%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] tenantId=%X{tenantId:-}"

logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"