apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config-log
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #log levels
  logging.level.root: "WARN"
  logging.level.org.goafabric: "INFO"

  logging.level.org.springframework: "INFO"
  logging.level.org.flywaydb.core: "INFO"
  logging.level.org.hibernate.SQL: "INFO"
