#application
server:
  port: 50900
  tomcat.max-threads: 20

#monitoring
management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "health,prometheus,heapdump"

springdoc.swagger-ui.path: /swagger-ui/index.html

#jaeger / zipkin
spring.zipkin.service.name: "person-service"
spring.sleuth.enabled: false
spring.zipkin.enabled: false

#security
security.authentication.enabled: true

#keycloak
keycloak:
  auth-server-url: http://localhost:30100/auth
  realm: 
  resource: callee-service
  public-client: true


#logging
logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

#logging.pattern.console: "%white(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"

