name: Renovate
on:
#  schedule:
#    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches:
      - renv
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
