#application
server:
  port: 50900
  tomcat.threads.max: 20

#logging
logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

#camunda
spring.datasource.url: jdbc:h2:mem:camunda

camunda.bpm.admin-user:
  id: demo
  password: demo

#links
## https://start.camunda.com (initializer)
## bpmn.io (bpmn online editor)
## https://camunda.com/platform/zeebe/ (camunda 8 successor)

