version: "3.7"

services:
  callee-service:
    container_name: ${STACK_NAME}-application
    image: goafabric/callee-service-native:1.0.6-SNAPSHOT
#    image: goafabric/callee-service${_Values_server_arch}:1.0.6-SNAPSHOT
    restart: 'no'
    ports:
      - "50900:50900"
    entrypoint: ["/workspace/org.goafabric.calleeservice.Application", "-Xmx${SERVICE_MEM}"]
#    entrypoint: ["java","-Xms${SERVICE_MEM}","-Xmx${SERVICE_MEM}","-cp","/app/resources:/app/classes:/app/libs/*","org.goafabric.calleeservice.Application"]
#    healthcheck:
#      test: "curl -f http://localhost:50900/actuator/health || exit 1"
#      interval: 15s
#      timeout: 10s
#      retries: 5
    volumes:
      - applogs:/usr/share/logs
    networks:
      - ${STACK_NAME}-net
    environment:
      #application
      - TZ=Europe/Berlin
      - server.port=50900
      - tomcat.max-threads=20
      - security.authentication.enabled=false
      #monitoring
      - management.endpoint.health.show-details=always
      - management.endpoints.web.exposure.include=health,prometheus,heapdump
      #logging
      - logging.level.root=WARN
      - logging.level.org.springframework=INFO
      - logging.level.org.goafabric=INFO
      - logging.file.max-size=10MB
      - logging.file.name=/usr/share/logs/application.log

volumes:
    applogs:

networks:
  callee-service-net:
    driver: bridge