version: "3.7"

services:
  calle-service:
    # wee need to set the container name if one container wants to call the other by name
    # we need to add the STACK Name because the container name needs to be unique inside the whole docker cluster
    # and with this option we can also be tenant aware
    container_name: calle-service_${STACK_NAME}
    image: goafabric/calle-service${ARCH_SUFFIX}:1.0.1-SNAPSHOT
    restart: 'no'
    ports:
      - "50900:50900"
    environment:
      - security.authentication=false
    healthcheck:
      test: "curl -f http://localhost:50900/actuator/health || exit 1"
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - applogs:/app/logs
    networks:
      - calle-service-net

#    network_mode: bridge

volumes:
    applogs:

networks:
  calle-service-net:
    driver: bridge