version: "3.7"

services:
  callee-service:
    container_name: callee-service_${STACK_NAME}
    image: goafabric/callee-service-native:1.0.6-SNAPSHOT
#    image: goafabric/callee-service${ARCH_SUFFIX}:1.0.6-SNAPSHOT
    restart: 'no'
    ports:
      - "50900:50900"
    entrypoint: ["/workspace/org.goafabric.calleeservice.Application", "-Xmx${SERVICE_MEM}"]
#    entrypoint: ["java","-Xms${SERVICE_MEM}","-Xmx${SERVICE_MEM}","-Djava.security.egd=file:/dev/./urandom","-cp","/app/resources:/app/classes:/app/libs/*","org.goafabric.calleeservice.Application"]
#    healthcheck:
#      test: "curl -f http://localhost:50900/actuator/health || exit 1"
#      interval: 15s
#      timeout: 10s
#      retries: 5
    volumes:
      - applogs:/app/logs
    networks:
      - callee-service-net
    environment:
      - TZ=Europe/Berlin
      - security.authentication.enabled=false
volumes:
    applogs:

networks:
  callee-service-net:
    driver: bridge