#!/bin/bash
source .values
source ../../../gradle.properties

export _Values_image_tag=${version}
export COMMAND=$1
export OPTION=$2

export _Values_image_native="" && [[ "${OPTION}" = "-native" ]] && export _Values_image_native=-native && export _Values_resources_entrypoint=${_Values_resources_entrypoint_native} && export _Values_health_check_disabled=true

function func_compose {
    echo Going $1 ...
    docker-compose -p ${_Values_root_name} -f ./templates/docker-compose.yml --env-file .values $1 $2 $3 $4 $5
}

if [ "${COMMAND}" = "up" ]
then
    func_compose up -d
elif [ "${COMMAND}" = "down" ]
then
    func_compose down
elif [ "${COMMAND}" = "restart" ]
then
    func_compose down
    func_compose up -d
elif [ "${COMMAND}" = "pull" ]
then
    func_compose down
    func_compose pull
elif [ "${COMMAND}" = "build" ]
then
    func_compose build
elif [ "${COMMAND}" = "prune" ]
then
    func_compose down --volumes
elif [ "${COMMAND}" = "update" ]
then
    func_compose down --volumes
    func_compose pull
    func_compose up -d
else
    echo Doing nothing !
fi

#CleanUp: docker volume prune