name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: "check"
          path: |
            ~/.gradle/caches          

      - name: Owasp
        run: gradle test dependencyCheckAnalyze

      - name: Sonar
        run: gradle test sonar -Dsonar.plugins.downloadOnlyRequired=true -Dsonar.dependencyCheck.htmlReportPath=build/reports/dependency-check-report.html -D-Dsonar.dependencyCheck.jsonReportPath=build/reports/dependency-check-report.json -Dsonar.dependencyCheck.securityHotspot=true -Dsonar.host.url=https://v2202402203466256255.megasrv.de/sonar  -Dsonar.login=admin -Dsonar.password=admin1

