name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: true == true
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Sonar
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: clean test sonar -Dsonar.host.url=http://v2202402203466256255.megasrv.de:9000 -Dsonar.login=admin -Dsonar.password=admin1
          #-Dsonar.login=squ_b2e14d8bcdd91f65e98b2e674ef9e3102375238d