name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}   
    - uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
#    - name: JVM Build
#      run: mvn -B clean deploy -P docker-image --file pom.xml
#    - name: Native Build
#      run: mvn -B clean deploy -P docker-image-native --file pom.xml
#    - name: Validate Gradle wrapper
#      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#    - name: Multiarch Image
#      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#      with:
#        arguments: jib jib
#    - name: Native Image
#      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#      with:
#        arguments: bootBuildImage     
    - name: Multiarch Image
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
        arguments: jib jib
  
