name: Renovate
on:
  push:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Renovate
        if: github.ref == 'refs/heads/main'
        uses: renovatebot/github-action@v40.3.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'info'

      - name: Merge main
        if: github.ref == 'refs/heads/autoupdate'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git merge origin/main && git push
