name: Renovate Test
on:
  push:
    branches:
      - autoupdate

jobs:
  renovate-test:
#    if: github.actor == 'Renovate Bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git merge origin/main && git push

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.1

      - name: Test
        run: gradle build test dockerImageNative -PnoPush
